---

- hosts: melder
  remote_user: ubuntu

  tasks:

  - name: ensure that torch is deleted
    file: path=~/torch state=absent

  - name: ensure the torch repo is cloned
    git: repo=https://github.com/torch/distro.git
         dest=~/torch
         recursive=yes
         force=yes
         accept_hostkey=yes

  - name: ensure torch's dependencies are installed
    shell: ./install-deps
           chdir=~/torch

  - name: ensure torch is installed
    shell: ./install.sh -b
           chdir=~/torch

  - name: ensure protobuf is installed
    apt: name={{ item }}
         state=latest
         update_cache=yes
    with_items:
      - libprotobuf-dev
      - protobuf-compiler
    become: yes
    become_method: sudo

  - name: ensure relevant luarocks are installed
    command: ~/torch/install/bin/luarocks install {{ item }}
    with_items:
      - loadcaffe
      - cunn
      - cutorch

  - name: ensure the neural-style repo is cloned
    git: repo=https://github.com/jcjohnson/neural-style.git
         dest=~/neural-style

  - name: ensure the models are downloaded
    command: bash models/download_models.sh
             chdir=~/neural-style

  - name: ensure the styles directory has been copied to remote host
    copy: src=styles dest=~/neural-style
